// Generated by scripts/generate-catalog.mjs. Do not edit directly.
export const marketplaceName = "israel-codex-plugins" as const;
export const plugins = [
  {
    "slug": "knowledge-work-superpowers",
    "name": "Knowledge Work Superpowers",
    "shortDescription": "Evidence-first workflows for research, analysis, writing, and delivery",
    "longDescription": "Frame substantial knowledge work, plan it, research systematically, test claims against evidence, draft from sources, review the result, and verify it before delivery.",
    "description": "A disciplined workflow system for research, analysis, writing, review, and evidence-backed delivery.",
    "version": "0.1.0",
    "category": "Productivity",
    "license": "MIT",
    "capabilities": [
      "Interactive",
      "Read",
      "Write"
    ],
    "defaultPrompts": [
      "Research this question deeply and build an evidence-backed brief.",
      "Turn this rough request into a clear knowledge-work plan.",
      "Audit this draft for unsupported claims and missing evidence."
    ],
    "skills": [
      {
        "name": "dispatching-parallel-research",
        "description": "Use when permitted multi-agent research has two or more independent question domains that can run concurrently without shared writes."
      },
      {
        "name": "drafting-from-evidence",
        "description": "Use when writing a report, brief, memo, comparison, recommendation, or synthesis from researched sources and verified claims."
      },
      {
        "name": "evidence-first-analysis",
        "description": "Use when important claims, comparisons, conclusions, or recommendations must be tested against evidence before drafting."
      },
      {
        "name": "executing-knowledge-work-plans",
        "description": "Use when a written research, analysis, writing, or delivery plan is ready for staged execution and checked progress."
      },
      {
        "name": "finishing-a-deliverable",
        "description": "Use when verified knowledge work needs final packaging, versioning, evidence preservation, limitations, and a clear handoff."
      },
      {
        "name": "framing-knowledge-work",
        "description": "Use when substantial research or writing lacks a clear outcome, audience, scope, source of truth, constraints, or success criteria."
      },
      {
        "name": "planning-knowledge-work",
        "description": "Use when an approved brief needs a concrete research, analysis, writing, or delivery plan with evidence and verification steps."
      },
      {
        "name": "receiving-work-review",
        "description": "Use when feedback arrives on a knowledge-work deliverable and each finding must be checked before revision."
      },
      {
        "name": "reviewing-knowledge-work",
        "description": "Use when a report, brief, memo, analysis, recommendation, or research package needs requirements and evidence review before delivery."
      },
      {
        "name": "systematic-research",
        "description": "Use when deep research, current or disputed facts, fact checking, literature review, or a multi-source investigation needs primary evidence."
      },
      {
        "name": "using-knowledge-work-superpowers",
        "description": "Use when substantial non-coding work needs research, analysis, planning, writing, review, or evidence-backed delivery. Skip for simple lookups."
      },
      {
        "name": "verification-before-delivery",
        "description": "Use when substantial knowledge work is about to be called complete, accurate, ready, or verified and needs fresh evidence checks."
      }
    ],
    "counts": {
      "skills": 12,
      "assets": 6,
      "references": 0,
      "scripts": 1,
      "files": 26
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "outcome-engine",
    "name": "Outcome Engine",
    "shortDescription": "Turn unclear goals into verified results.",
    "longDescription": "Clarify decisions, write durable briefs, create independent action slices, execute from evidence, and improve the systems behind the work.",
    "description": "Turn unclear goals into verified outcomes across research, writing, operations, creative work, personal planning, and software.",
    "version": "1.0.0+codex.20260710154316",
    "category": "Productivity",
    "license": "MIT",
    "capabilities": [
      "Reason",
      "Write",
      "Analyze"
    ],
    "defaultPrompts": [
      "Grill me on this idea before I commit.",
      "Turn this conversation into an outcome brief.",
      "Run Outcome Engine from idea to verified result."
    ],
    "skills": [
      {
        "name": "decision-grill",
        "description": "Interview the user one consequential question at a time to resolve an idea, plan, workflow, research question, or design. Use when they say grill me, pressure-test this, challenge my plan, clarify the brief, or ask hard questions. Inspect sources before asking discoverable facts and track dependent decisions."
      },
      {
        "name": "evidence-driven-delivery",
        "description": "Execute approved work one observable result at a time through a check-change-verify loop. Use when the user asks to implement a plan, complete an action slice, work test-first, prove each step, or finish a bounded result. Adapt proof to research, writing, creative work, operations, data, personal plans, or software."
      },
      {
        "name": "improve-system-architecture",
        "description": "Review a workflow, project, knowledge base, operating process, plugin, product, or codebase for structural friction. Use when the user asks for an architecture review, system audit, workflow cleanup, clearer ownership, better information flow, fewer handoffs, deeper modules, or a system agents can follow. Present evidence-backed changes without implementing them unless asked."
      },
      {
        "name": "outcome-engine",
        "description": "Coordinate a path from unclear idea to verified result across research, writing, creative work, operations, planning, and software. Use when the user asks to run Outcome Engine, take an idea from start to finish, turn a fuzzy goal into a plan, resume a multi-phase workflow, or combine clarification, briefing, action slicing, evidence-first delivery, and system review."
      },
      {
        "name": "to-action-slices",
        "description": "Break an approved brief, plan, or goal into independently verifiable action slices with blockers. Use when the user asks for tasks, tickets, work packages, delegation units, or parallel work. Favor narrow end-to-end outcomes, handle wide changes with expand-migrate-contract sequencing, and validate local JSON dependency plans."
      },
      {
        "name": "to-outcome-brief",
        "description": "Turn settled conversation, notes, research, or decisions into an execution-ready outcome brief. Use when the user asks for a specification, campaign brief, research brief, creative brief, or project brief from understood context. Synthesize without reopening settled questions and validate local Markdown briefs before handoff."
      }
    ],
    "counts": {
      "skills": 6,
      "assets": 3,
      "references": 3,
      "scripts": 2,
      "files": 18
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "proofloop",
    "name": "ProofLoop",
    "shortDescription": "Run evidence-gated learning loops.",
    "longDescription": "ProofLoop adds bounded task execution, quarantined learning records, governed memory review, and read-only audits without adding external authority.",
    "description": "Governed agent learning ledger and evaluation wrapper with bounded refinement, verification, quarantined memory, and read-only audit.",
    "version": "0.1.0+codex.20260713133858",
    "category": "Productivity",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Run this task through ProofLoop.",
      "Review these ProofLoop candidate lessons.",
      "Audit whether ProofLoop is helping."
    ],
    "skills": [
      {
        "name": "proofloop-audit",
        "description": "Perform a read-only audit of ProofLoop outcomes, advisory retrieval effects, verifier calibration, memory quality, drift, security denials, cost, and portability. Use only when the user explicitly invokes $proofloop-audit or asks to audit ProofLoop learning or determine whether ProofLoop is helping."
      },
      {
        "name": "proofloop-memory-review",
        "description": "Inspect and adjudicate ProofLoop candidate lessons, approved advisory markers, preferences, conflicts, expiry, supersession, and local exclusions. Use only when the user explicitly invokes $proofloop-memory-review or asks to review, approve, reject, expire, narrow, supersede, or exclude ProofLoop memory."
      },
      {
        "name": "proofloop-run",
        "description": "Run an explicitly requested task through ProofLoop's bounded writer, judge, execution, verification, and quarantined-memory protocol. Use only when the user explicitly says ProofLoop, invokes $proofloop-run, or asks to apply the ProofLoop learning protocol. Do not trigger for generic planning, debugging, research, verification, or improvement requests."
      }
    ],
    "counts": {
      "skills": 3,
      "assets": 0,
      "references": 10,
      "scripts": 18,
      "files": 37
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "writing-quality",
    "name": "Writing Quality",
    "shortDescription": "Route and verify serious writing work.",
    "longDescription": "Writing Quality separates intent architecture, rewriting, detect-only review, claim support, and final prose validation so each request receives the smallest sufficient intervention.",
    "description": "Intent-aware drafting, rewriting, detect-only review, claim boundaries, and final prose validation.",
    "version": "0.1.0+codex.20260714115137",
    "category": "Productivity",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Route this writing task and produce the requested result.",
      "Review this draft without rewriting it.",
      "Check the factual claim boundaries in this draft."
    ],
    "skills": [
      {
        "name": "business-writing-intent-enforcer",
        "description": "Use for memos, specs, PRDs, operating docs, executive summaries, proposals, project plans, and structured business deliverables where reader intent, decisions, actionability, and evidence matter."
      },
      {
        "name": "claim-boundary-checker",
        "description": "Separates supported, unsupported, uncertain, and non-factual statements in prose. Use when editing or drafting could introduce factual claims beyond supplied sources, when a user asks for a claim audit, or when current and high-stakes facts need explicit boundaries. Produces a validated claim ledger without turning ordinary writing work into unnecessary research."
      },
      {
        "name": "writing-enforcer",
        "description": "Unified writing enforcer that removes AI patterns, preserves voice, injects soul, and ensures plain human-sounding prose. Combines humanizer, output-quality-enforcer, and anti-AI style detection into one workflow. Use when asked to humanize this, remove AI feel, make this sound like me, clean this up, too robotic, too generic, sound more human, or to improve any text that reads as AI-generated or over-polished. Two modes: DETECT (flag patterns only) and REWRITE (full pipeline, default). Applies Israel's law: simpler words always beat complex words. Enforces voice, soul, intent, and the 36-pattern AI-tell taxonomy. Runs deterministic scripts for em-dash removal and quality scoring."
      },
      {
        "name": "writing-quality-router",
        "description": "Routes writing requests to intent architecture, rewriting, detect-only review, or validation. Use when a user asks to draft, rewrite, tighten, humanize, review, or quality-check prose and the correct degree of intervention is unclear. Preserves source claims, separates diagnosis from mutation, and validates the route before execution."
      }
    ],
    "counts": {
      "skills": 4,
      "assets": 3,
      "references": 14,
      "scripts": 7,
      "files": 33
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "capability-operator",
    "name": "Capability Operator",
    "shortDescription": "Route, inventory, and govern Codex capabilities.",
    "longDescription": "Capability Operator selects one primary plugin or skill route, inventories capability layers, finds overlap and drift, manages lifecycle decisions, builds validated skills, and proves clean-task discovery after installation.",
    "description": "Capability routing, read-only inventories, overlap audits, portfolio governance, skill creation, and fresh-task discovery proof.",
    "version": "0.1.0+codex.20260714193616",
    "category": "Productivity",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Choose the right plugin or skill for this request.",
      "Inventory my current Codex capabilities.",
      "Audit skill overlap without changing anything.",
      "Verify that this plugin is visible in a clean task."
    ],
    "skills": [
      {
        "name": "capability-inventory",
        "description": "Builds a read-only inventory of loose skills, plugin source bundles, installed plugins, caches, and optional task-visible capabilities. Use before global skill or plugin work, after installs, or when filesystem presence and Codex visibility may disagree. Emits exact paths and fingerprints so later audits can distinguish duplicates from drift."
      },
      {
        "name": "capability-router",
        "description": "Routes unclear, multi-stage, or cross-plugin Codex requests to one primary personal plugin or owned skill, with bounded companions, handoffs, exclusions, load order, and verification needs. Use when plugin versus skill ownership is unclear, several personal plugins overlap, a request spans capability domains, or the harness needs a deterministic routing decision. Explicit user selections still win, and focused requests should call the narrow owned skill directly."
      },
      {
        "name": "fresh-task-discovery-verifier",
        "description": "Proves that newly installed plugin skills appear in a clean Codex task prompt. Use after plugin install, reinstall, cache update, or visibility debugging. Checks expected names against fresh prompt input and returns machine-readable missing and found sets, preventing stale open-task inventories from being mistaken for installation failure."
      },
      {
        "name": "harness-meta-audit",
        "description": "Run deep meta-audits against the user's AI harness and work system. Three routed modes. HARNESS audits goal alignment, Bitter Lesson over-engineering, self-model staleness, memory compounding, eval design, and the autonomy ladder. SECURITY maps prompt-injection exposure per input avenue and maintains a living attack-surface inventory. LIFE runs the ikigai big-picture, steelman-my-biggest-bet, 10x-or-dies, decisions-into-policy, binding-constraint, and bus-factor audits. Use whenever the user says audit my harness, self-model audit, bitter lesson check, is my memory compounding, autonomy ladder, attack surface, prompt injection review, where am I most wrong, find my bottleneck, bus factor, or asks for any deep review of their setup, priorities, or system design. Rerun after every major model intelligence jump."
      },
      {
        "name": "plugin-portfolio-manager",
        "description": "Maintains a decision ledger for personal plugins, their owned skills, companions, tests, versions, and retirement state. Use when planning, building, auditing, upgrading, or retiring multiple plugins. Validates ownership and lifecycle fields so plugin bundles remain intentional instead of becoming untracked collections of copied skills."
      },
      {
        "name": "skill-creator-pro",
        "description": "Professional-grade skill creation framework with 3-tier architecture (simple, complex, agentic), eval/iteration loop with grading agents and interactive review, reliability patterns, deep discovery, MCP integration guidance, and Anthropic-aligned best practices. Use when creating new skills or updating existing skills that need to work reliably, handle edge cases, use appropriate tools (scripts for deterministic accuracy, templates for consistency), validate outputs, anticipate failure modes, or coordinate across MCP servers. Includes tier selection framework, orchestrator/router patterns for agentic skills, structured eval loop with benchmark aggregation, description optimization pipeline, blind A/B comparison, and production-grade quality gates. Triggers on skill creation, skill update, build a skill, create a skill, improve skill, test a skill, run evals, benchmark skill, optimize description, or any request to package Claude workflows into reusable skills."
      },
      {
        "name": "skill-overlap-audit",
        "description": "Finds duplicate, drifted, mirrored, and collision-prone skills across loose roots and plugin bundles. Use before bundling skills, retiring loose copies, resolving conflicting triggers, or auditing why multiple similarly named skills appear. Consumes a capability inventory and reports exact fingerprints without mutating any source."
      }
    ],
    "counts": {
      "skills": 7,
      "assets": 8,
      "references": 14,
      "scripts": 19,
      "files": 61
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "agent-ops",
    "name": "Agent Ops",
    "shortDescription": "Operate agents, Goals, and bounded loops.",
    "longDescription": "Agent Ops routes agent design, Goal engineering, execution, resume, bounded loops, and system audits while requiring explicit boundaries, stops, evidence, and recovery.",
    "description": "Design, run, resume, and audit agents, Goals, and bounded loops with explicit authority and evidence.",
    "version": "0.1.0+codex.20260714115137",
    "category": "Productivity",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Design a bounded agent system for this outcome.",
      "Turn this sustained task into a verifiable Goal.",
      "Audit this agent system before it runs."
    ],
    "skills": [
      {
        "name": "agent-builder",
        "description": "Build agents and agentic workflows for Claude Code and Codex CLI from a plain task description. Based on Anthropic's Building Effective Agents framework. Five routed modes. ARCHITECT walks the simplicity ladder and selects the pattern. WORKFLOW builds the chosen pattern as concrete artifacts. AGENT builds autonomous agents with ground-truth verification, stop conditions, pause points, and Claude Code subagent files. ACI designs and hardens tool definitions (poka-yoke, docstring-grade parameters). REVIEW critiques existing agent setups against the three core principles. Harness-aware, built agents inherit AGENTS.md chains, CLAUDE.md contracts, and output-folder discipline. Triggers on build an agent, design an agent, make me a subagent, agent for claude code or codex, codex subagent config, multi-agent system, orchestrator workers, prompt chain, evaluator optimizer, agent design patterns, review or fix my agent, tool definition design, ACI, or any request to create an agentic system."
      },
      {
        "name": "agent-ops-router",
        "description": "Routes requests among agent design, workflow design, Goal engineering, bounded loop execution, audit, run, and resume. Use when a request mentions agents, autonomous workflows, persistent Goals, monitoring loops, retries, handoffs, or resuming an existing system. Enforces one primary operational route and prevents a general outcome workflow from being mistaken for an agent-system design."
      },
      {
        "name": "agent-system-audit",
        "description": "Audits an agent, Goal, loop, or autonomous workflow for authority, stop conditions, evidence, tool contracts, cost controls, recovery, and durable state. Use for read-only reviews before launch, after failures, or before increasing autonomy. Produces a validated finding ledger with severity and evidence, without executing or repairing the system unless separately authorized."
      },
      {
        "name": "goal-runner",
        "description": "Run a task to evidence-gated completion. Takes any deliverable task, converts it into a durable goal contract (outcome, machine checks, judgment criteria, four stops, iteration policy), then drives an execute-verify loop that never reports done unless a deterministic check script passes and a fresh-context verifier that did not do the work confirms every criterion. Never dies silently, it finishes or stops with a blocked report naming what would clear the block. Four routed modes. CONTRACT builds the goal contract. RUN executes the loop. VERIFY checks any existing deliverable against a spec. RESUME continues an interrupted run from the contract and progress files. Triggers on run this as a goal, goal runner, run to completion, make sure this is absolutely complete, don't stop until done, finish this fully, completion contract, verify this against the brief or spec, evidence-gated done, resume the goal run, or any task where completion must be guaranteed rather than claimed."
      },
      {
        "name": "loop-goal-engineer",
        "description": "Write production-ready /goal and /loop prompts for Claude Code and Codex CLI. User describes a thing they want done, this skill engineers the goal condition, the loop, or both. Four routed modes. GOAL writes a one-shot verifiable finish line. LOOP writes a recurring or self-pacing loop with all six working parts (trigger, execution, verifier, stop rules, memory, skills). ORCHESTRATE writes multi-agent goal setups (orchestrator, builder, reviewer) across Codex and Claude Code. DIAGNOSE fixes loops that run away, stall, or waste tokens. Triggers on write a goal, write a loop, /goal, /loop, goal condition, loop engineering, turn this into a loop, make this autonomous, codex goal, claude code loop, schedule a loop, stop rules, fix my loop, my loop ran away, orchestrate codex and claude, or any request to convert a task into an autonomous agent loop or goal."
      },
      {
        "name": "loopy",
        "description": "Discover, find, compare, audit, repair, adapt, craft, run, debrief, save, and prepare repeatable AI-agent loops for publication. Use when a user asks to analyze code or coding threads for recurring work, find a published loop, interview them to turn a goal into a bounded loop, review a loop for weak checks or unsafe authority, execute a loop with an evidence receipt, learn from completed runs, save or reuse a project loop, or validate and submit a loop to Loop Library."
      }
    ],
    "counts": {
      "skills": 6,
      "assets": 8,
      "references": 17,
      "scripts": 7,
      "files": 55
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "video-production-studio",
    "name": "Video Production Studio",
    "shortDescription": "Plan, produce, and verify video assets.",
    "longDescription": "Video Production Studio routes briefs across explainers, launches, music, slideshows, website and PR stories, captions, overlays, prompts, HyperFrames implementation, and final delivery checks.",
    "description": "End-to-end routing, prompting, production, captions, graphics, runtime implementation, and delivery checks for video.",
    "version": "0.1.0+codex.20260714115922",
    "category": "Media",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Route this brief into a complete video production plan.",
      "Turn this product launch into a finished video workflow.",
      "Run delivery QC on this rendered video."
    ],
    "skills": [
      {
        "name": "embedded-captions",
        "description": "Add captions to a talking-head video. ONE catalog (CATALOG.md) of 32 visual identities behind two engines: column-flow (captions composited INTO the scene - matte occlusion + mix-blend; cream/ink/editorial/keynote/documentary/loud/neon/glitch/chrome/velocity) and themed constitutions (anchor/ordnance/terminal/neonsign/stardust/stomp/scoreboard/transit/vhs/arcade/dossier/laser/thunder/hologram/biolume/aurora/spectrum/papercut/popup/chalkboard/graffiti/brush/inkwater/ransom/lastpage/nightcity - e.g. a glyph-decode climax, a neon sign WRITTEN stroke by stroke, or the quiet `anchor` rail default). Route by identity, never by mode. Trigger on \"captions/subtitles\", \"embed/cinematic captions\", \"VFX captions\", \"炸/特效/酷炫字幕\", a named identity, or top-tier motion-graphics asks. Embedding every word is wrong for most talking-head content - `anchor` is the verbatim default. Pipeline: transcription → hyperframes remove-background matting → HTML render → ffmpeg overlay. Requires hyperframes and a single-subject clip."
      },
      {
        "name": "faceless-explainer",
        "description": "turn arbitrary text - an article, notes, a topic, a brief - into a faceless explainer video, up to ~3 min (sweet spot 30-90s), where every visual is invented (typography, abstract graphics, diagrams, data-viz) rather than captured. There is no URL, no website capture, and no real assets. Use this skill for topic explainers, concept breakdowns, how-tos, listicles, and narrative explainers. Do not use it for a product launch/promo (use /product-launch-video), a tour of a real website (use /website-to-video), a GitHub PR (use /pr-to-video), captions on existing footage (use /embedded-captions), or a short unnarrated motion graphic (use /motion-graphics). If the intent is unclear, route through /hyperframes first."
      },
      {
        "name": "general-video",
        "description": ">"
      },
      {
        "name": "graphic-overlays",
        "description": "Package an existing talking-head / interview / podcast video by layering timed, designed GRAPHIC OVERLAY cards onto the playing video - titles, lower-thirds, data callouts, quotes, side panels, picture-in-picture - synced to the transcript. The source video plays in full; the agent designs and writes each card's HTML in conversation, then renders to MP4 via hyperframes. Use when the user asks for graphic overlays, on-screen graphics / lower-thirds / data callouts / kinetic titles on a video, \"package / dress up my video\", \"add overlay cards / graphic cards\", or AI-composed graphic packaging of an existing video. NOT for plain subtitles (→ embedded-captions) or building a video from scratch (→ the creation workflows); when unsure overlays-vs-captions, see /hyperframes."
      },
      {
        "name": "media-use",
        "description": "Agent Media OS: resolve any media need (BGM, SFX, image, icon) into a frozen local file plus ledger record. One verb (`resolve`) handles the full cascade: project cache, global cache, HeyGen catalog search, freeze, register. Keeps search noise on disk, hands the agent a path. Use when a composition needs background music, sound effects, images, or icons."
      },
      {
        "name": "motion-graphics",
        "description": ">"
      },
      {
        "name": "music-to-video",
        "description": "Use when the user has a music track (an audio file, or a video to pull audio from) and wants a beat-synced HyperFrames video, calm to hard-hitting. The music drives everything: one analyzer reads it once, the orchestrator lays out the frames and fills a per-frame plan, and one sub-agent builds each frame. Typography and templates are the floor - a complete video needs zero assets - but any images or videos the user supplies are cut into the frames on the same beat grid (beat-cut / ken-burns). The genre (lyric video, slideshow, kinetic promo) falls out of the per-frame choices; the pipeline never branches on it."
      },
      {
        "name": "pr-to-video",
        "description": "Turn a GitHub pull request URL, repository pull-request reference, or the current checked-out PR into a code-change explainer video up to about three minutes. Use for changelogs, feature reveals, fixes, and refactor walkthroughs rendered from diffs, commits, and files. The input is a code change read with the GitHub CLI, not a website capture. Route launches, website tours, topic explainers, captions, and short motion graphics to their specialist skills."
      },
      {
        "name": "product-launch-video",
        "description": "turn a product or marketing URL, pasted script, or brief into a product launch video, including SaaS promos, feature reveals, app launches, company promos, and product marketing videos. Use this skill when the user wants to market, launch, promote, or reveal a product. Do not use it for general non-launch website tours, non-product topic explainers, GitHub pull requests, captioning existing footage, or short unnarrated motion graphics. If the intent is unclear, route through /hyperframes first."
      },
      {
        "name": "remotion-to-hyperframes",
        "description": "Port an existing Remotion (React) composition to HyperFrames HTML. Use ONLY when the user explicitly asks to port/convert/migrate/translate a Remotion source. Do NOT use: (a) authoring a new HyperFrames composition; (b) Remotion mentioned in passing; (c) Remotion code shared as reference only; (d) \"same video as my Remotion one\" without explicit migrate request - treat as fresh build. Doubt → `/general-video`. One-way, Remotion-only: no reverse export (HyperFrames→Remotion or any framework), no non-Remotion source (After Effects, Framer Motion, plain React/CSS) → out of scope, re-create via `/general-video`. Flags unsupported patterns (useState, useEffect, async calculateMetadata, third-party React libs, `@remotion/lambda`) and recommends runtime interop over lossy translation. Unsure whether to port vs. build fresh, or only a passing Remotion mention? → /hyperframes."
      },
      {
        "name": "slideshow",
        "description": ">"
      },
      {
        "name": "video-delivery-qc",
        "description": "Verifies rendered video files against delivery requirements, including readable media metadata, dimensions, duration, audio presence, caption evidence, source-to-output consistency, and visual inspection. Use before handing off any video export. Includes deterministic ffprobe checks and a human inspection checklist, and reports untested requirements rather than claiming a render passed."
      },
      {
        "name": "video-production-router",
        "description": "Routes video requests to concept, script, prompt, footage, captions, overlays, motion graphics, music visualization, slideshow, product launch, PR, website capture, or runtime implementation. Use when a video brief spans multiple production skills or the correct production path is unclear. Produces a validated route and explicit runtime choice before asset generation or rendering begins."
      },
      {
        "name": "video-prompt-builder",
        "description": "Build cinematic, shot-by-shot video prompts with full effects breakdowns. Four modes. BUILD: creative brief to shot-by-shot prompts with effects timeline, inventory, density map, energy arc. ANIMATE: image-to-video, keyframe interpolation (start+end frame), Seedance 2.0 native multi-image multi-shot prompts (@imageN syntax for up to 9 images in one prompt), and role-based multi-reference composition (subject/style/environment). DECONSTRUCT: reverse-engineer a described video into structured effects format. REMIX: transplant effects architecture onto a new subject or brand. Each shot prompt output in its own code block. Optimized for Seedance 2.0, Kling 3, Veo 3, Sora 2. Triggers on video prompt, shot list, effects breakdown, brand film, ad prompt, animate this, image to video, keyframe, multi-image seedance, @image prompt, deconstruct video, remix video, or any visual concept needing generation-ready video prompts."
      },
      {
        "name": "website-to-video",
        "description": "Capture a general website/URL and turn it into a HyperFrames video (site tour, showcase, or social clip from the site's own visuals). Uses headless Chrome screenshots + brand assets. Use when intent is general - portfolio/blog/landing-page showcase or social clip from the site. NOT for: product/SaaS launch or promo (→ /product-launch-video, even from a URL); topic explainer with no site (→ /faceless-explainer); GitHub PR (→ /pr-to-video); adding captions to existing video (→ /embedded-captions); short unnarrated page-highlight motion graphic (→ /motion-graphics). Unclear launch-vs-general-site? Ask one question or start at /hyperframes."
      }
    ],
    "counts": {
      "skills": 15,
      "assets": 157,
      "references": 206,
      "scripts": 91,
      "files": 532
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "web-product-studio",
    "name": "Web Product Studio",
    "shortDescription": "Build and verify coherent web products.",
    "longDescription": "Web Product Studio routes greenfield builds, redesigns, image-first implementation, targeted fixes, and QA while enforcing one design constitution and browser-verifiable acceptance flows.",
    "description": "Route, build, redesign, implement from images, and verify web products with one visual authority.",
    "version": "0.1.0+codex.20260714115137",
    "category": "Developer Tools",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Route and build this web product from the brief.",
      "Redesign this existing interface and verify the main flows.",
      "Turn this screenshot into a working web surface."
    ],
    "skills": [
      {
        "name": "acceptance-flow",
        "description": "Converts a web product brief into browser-verifiable user flows with preconditions, actions, expected observations, evidence, and failure states. Use before implementation or QA when completion needs to be proven through rendered behavior. Produces a validated acceptance-flow JSON that can guide manual Browser checks or Playwright automation."
      },
      {
        "name": "code-production-agent",
        "description": "Production-grade coding agent for non-coders. Transforms plain English into working software through mandatory research, planning, approval, and validated execution. Handles building new apps/features/components/APIs, debugging and refactoring existing code, system design, performance optimization, and clean architecture restructuring. Five subagents (Planner, Builder, Fixer, Designer, Reviewer) coordinate through strict phase workflow. Includes deterministic code validation scripts for linting, error scanning, complexity analysis, structure checks. Use when user says \"build me\", \"create an app\", \"make a website\", \"fix this code\", \"debug this\", \"refactor\", \"optimize performance\", \"design a system\", \"clean up this codebase\", \"build an API\", \"create a component\", or describes any software idea or code problem in plain language. Also triggers on \"help me code\", \"I need software\", \"what's wrong with this code\", \"make this faster\", \"restructure this\", or any coding request from a non-technical user."
      },
      {
        "name": "design-constitution-selector",
        "description": "Selects exactly one visual design skill for a web product based on brand, audience, content density, product type, and supplied references. Use before frontend styling when several installed design systems could conflict. Records one selected constitution or none, validates the choice, and keeps non-selected style skills out of the implementation context."
      },
      {
        "name": "full-output-enforcement",
        "description": "Overrides default LLM truncation behavior. Enforces complete code generation, bans placeholder patterns, and handles token-limit splits cleanly. Apply to any task requiring exhaustive, unabridged output."
      },
      {
        "name": "gstack",
        "description": "Fast headless browser for QA testing and site dogfooding. Use when asked to browse or navigate a page, take a screenshot, inspect a rendered site, test a deployment, verify a user flow, or capture browser bug evidence."
      },
      {
        "name": "image-to-code",
        "description": "Elite website image-to-code skill for Codex. For visually important web tasks, it must first generate the design image(s) itself, deeply analyze them, then implement the website to match them as closely as possible. In Codex, it must prefer large, readable, section-specific images instead of tiny compressed boards, generate fresh standalone images for sections or detail views instead of cropping old ones, avoid lazy under-generation, avoid cards-inside-cards-inside-cards UI, and keep the hero clean, spacious, readable, and visible on a small laptop."
      },
      {
        "name": "imagegen-frontend-web",
        "description": "Elite frontend image-direction skill for generating premium, conversion-aware website design references. CRITICAL OUTPUT RULE - generate ONE separate horizontal image FOR EVERY section. A landing page with 8 sections produces 8 images. Never compress multiple sections into one image. Enforces composition variety (not always left-text / right-image), background-image freedom, varied CTAs, varied hero scales (giant / mid / mini minimalist), narrative concept spine, second-read moments, and a single consistent palette across all images. Optimized for landing pages, marketing sites, and product comps that developers or coding models can accurately recreate."
      },
      {
        "name": "playwright",
        "description": "Use when the task requires automating a real browser from the terminal (navigation, form filling, snapshots, screenshots, data extraction, UI-flow debugging) via `playwright-cli` or the bundled wrapper script."
      },
      {
        "name": "redesign-existing-projects",
        "description": "Upgrades existing websites and apps to premium quality. Audits current design, identifies generic AI patterns, and applies high-end design standards without breaking functionality. Works with any CSS framework or vanilla CSS."
      },
      {
        "name": "web-product-router",
        "description": "Routes web product requests to greenfield build, redesign, image-first implementation, targeted fix, or quality assurance. Use when a frontend or web app request could trigger several build and design skills. Selects one primary path, one design constitution, and browser-verifiable acceptance flows before implementation."
      }
    ],
    "counts": {
      "skills": 10,
      "assets": 7,
      "references": 7,
      "scripts": 6,
      "files": 41
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "model-prompt-lab",
    "name": "Model Prompt Lab",
    "shortDescription": "Route, build, migrate, and test model prompts.",
    "longDescription": "Model Prompt Lab selects a verified model and prompt operation before loading focused production guidance, then supports migration audits and benchmark design without inventing unstable platform behavior.",
    "description": "Verified model routing, production prompt architecture, migration audits, and benchmark design.",
    "version": "0.1.0+codex.20260714121935",
    "category": "Developer Tools",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Route this prompt job to the right verified model workflow.",
      "Audit this prompt before migrating it to another model.",
      "Design a representative benchmark for this production prompt."
    ],
    "skills": [
      {
        "name": "fable-5-production-prompter",
        "description": "Generate, migrate, diagnose, and harden production prompts for Claude Fable 5 and Mythos 5 (claude-fable-5). Four routed modes. GENERATE builds new Fable 5 prompts with effort-aware defaults plus anti-overplanning, scope-restraint, and brevity guards. MIGRATE converts Opus 4.8/4.7/4.6 prompts and over-prescriptive skills via subtract-first depruning and reasoning-echo removal. DIAGNOSE fixes behavior drift (overplanning, fabricated progress, early stopping, context-budget anxiety, unrequested actions, refusal fallbacks, unreadable summaries). LONG-RUN builds multi-hour and multi-day autonomous harnesses with memory systems, verifier subagents, send_to_user tools, and parallel subagent orchestration. Covers effort levels, adaptive-thinking-only API, refusal stop reason with Opus 4.8 fallback, and dual-use safety classifiers. Triggers on Fable 5 prompt, Mythos 5, claude-fable-5, migrate to Fable 5, Claude 5 prompt, long-running agent harness, or any Fable 5 prompt engineering request."
      },
      {
        "name": "fable-mode",
        "description": ">-"
      },
      {
        "name": "gpt-5-4-production-prompter",
        "description": "Generate production-ready GPT-5.4 prompts, migrate prompts from GPT-5.2/5.3-Codex/4.1/o3/o4-mini, or troubleshoot existing GPT-5.4 prompt issues. Use when users request GPT-5.4 prompts, ChatGPT prompts, GPT Builder instructions, API system prompts, Responses API configs, or need help with agentic workflows, coding, web research, extraction, long-context, computer use, or frontend design. Also triggers on migration requests, prompt debugging, early stopping, scope drift, tool routing failures, phase parameter problems, or formatting drift. Covers 1M token context, native compaction, phase parameter, tool_search, computer use, xhigh reasoning, personality controls, research mode, citation gating, dependency-aware tool persistence, verification loops, completeness contracts, and frontend design patterns."
      },
      {
        "name": "gpt-5-6-production-prompter",
        "description": "Generate production-ready GPT-5.6 prompts (gpt-5.6-sol, gpt-5.6-terra, gpt-5.6-luna), migrate prompts from GPT-5.5/5.4/5.3-Codex/4.1/o3, or troubleshoot GPT-5.6 prompt issues. Use when users request GPT-5.6 prompts, ChatGPT prompts, GPT Builder instructions, API system prompts, Responses API configs, or need help with agentic workflows, coding agents, web research, extraction, long-context, computer use, or frontend design. Also triggers on migrate to gpt-5.6, port to 5.6, openai-docs migrate, prompt debugging, responses too brief, unnecessary approval requests, safeguard refusals on legit work, cache cost surprises, scope drift, tool routing failures, formatting drift. Covers lean prompting, Programmatic Tool Calling, pro mode, multi-agent beta, max reasoning effort, persisted reasoning, explicit prompt caching, autonomy and approval boundaries, verbosity contracts, retrieval budgets, citation gating, phase parameter, 1M context, compaction, frontend design."
      },
      {
        "name": "model-prompt-router",
        "description": "Routes production prompt work across generation, migration, diagnosis, benchmark design, and structured working-mode guidance for GPT-5.6, GPT-5.4, Fable 5, and related model families. Use when the requested model, prompt surface, effort, tool policy, or migration path is unclear. Requires current-source verification for unstable model behavior and validates one primary route before handoff."
      },
      {
        "name": "prompt-benchmark-designer",
        "description": "Designs reproducible prompt benchmarks with success, boundary, and failure cases, objective assertions, metrics, cost limits, and stopping rules. Use when comparing prompts, migrating models, testing tool behavior, or deciding whether a prompt change is production-ready. Produces a validated benchmark specification but does not claim results before runs occur."
      },
      {
        "name": "prompt-migration-audit",
        "description": "Audits a prompt migration for stale model assumptions, unsupported parameters, copied over-instruction, tool-policy drift, output-contract loss, and unverified current claims. Use when moving prompts between GPT, Fable, Mythos, Codex, ChatGPT, or API surfaces. Produces a validated finding ledger and verification list without silently rewriting the prompt."
      }
    ],
    "counts": {
      "skills": 7,
      "assets": 9,
      "references": 34,
      "scripts": 8,
      "files": 76
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "strategy-room",
    "name": "Strategy Room",
    "shortDescription": "Pressure-test decisions before committing resources.",
    "longDescription": "Strategy Room routes consequential choices through interview, assumption challenge, option generation, decision synthesis, and assumption tracking, then stops at an explicit execution handoff.",
    "description": "Pre-commitment interviews, assumption challenge, option generation, decision synthesis, and uncertainty tracking.",
    "version": "0.1.0+codex.20260714121935",
    "category": "Productivity",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Pressure-test this decision before I commit resources.",
      "Generate distinct options and synthesize a recommendation.",
      "Create an assumption register for this choice."
    ],
    "skills": [
      {
        "name": "assumption-challenger",
        "description": "Tier 3 research-first assumption challenger. Researches the subject deeply via web search to become a domain expert, builds a challenge plan, executes multi-lens scrutiny, triple-verifies findings against research, and ships a recommendations report. Use when user says \"challenge assumptions,\" \"analyze blind spots,\" \"what am I missing,\" \"critique this,\" \"find contradictions,\" \"stress test this,\" \"what could go wrong,\" \"tear this apart,\" or asks for rigorous adversarial review of plans, prompts, strategies, ideas, business cases, technical decisions, or AI prompts. Five-agent pipeline (researcher, planner, challenger, verifier, synthesizer). Three effort modes (light, standard, deep). Mandatory web search before challenge so the critique is grounded in current facts and expert disagreement, not training-data instinct."
      },
      {
        "name": "assumption-register",
        "description": "Creates and maintains a structured register of assumptions, evidence, confidence, reversibility, owners, test plans, and kill conditions. Use when a strategy, product plan, forecast, or decision depends on beliefs that may change. Validates unique assumption records and prevents unsupported certainty from disappearing into prose."
      },
      {
        "name": "decision-synthesizer",
        "description": "Turns interviews, research, challenged assumptions, and distinct options into one evidence-linked recommendation with risks, conditions, reversibility, confidence, and a clean handoff. Use when a decision has enough inputs but remains unresolved. Produces a validated decision record and keeps measured evidence separate from judgment."
      },
      {
        "name": "grill-me",
        "description": "Conduct rigorous, source-first interviews that turn vague or incomplete plans into shared, decision-ready specifications. Use when the user explicitly says \"grill me,\" \"interview me relentlessly,\" \"pressure-test this,\" \"ask me everything,\" \"walk the decision tree,\" or \"challenge every assumption\" before planning or execution across business, creative, research, writing, product, operations, personal, or coding work. Explore available files, codebases, documents, connected apps, and authoritative sources before asking questions; resolve dependent decisions branch by branch; and record decisions, assumptions, conflicts, and open issues. Do not use for ordinary requests that need only one or two clarifications."
      },
      {
        "name": "multi-direction-explorer",
        "description": "Use when Israel asks for options, angles, names, concepts, prompts, creative directions, strategy paths, or broad variation. Produces meaningfully different directions instead of minor wording changes, then helps choose the strongest path."
      },
      {
        "name": "strategy-room-router",
        "description": "Routes pre-commitment decision work to rigorous interview, assumption challenge, broad option generation, decision synthesis, or assumption tracking. Use when a product, business, creative, technical, or personal choice needs pressure-testing before resources are committed. Enforces a decision-only boundary and hands execution to Outcome Engine only after the recommendation is accepted."
      }
    ],
    "counts": {
      "skills": 6,
      "assets": 12,
      "references": 9,
      "scripts": 7,
      "files": 46
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "brand-world-studio",
    "name": "Brand World Studio",
    "shortDescription": "Turn approved positioning into a coherent visual world.",
    "longDescription": "Brand World Studio routes approved strategy into a visual brief, identity system, image-model choice, production prompt pack, and consistency review without inventing upstream positioning.",
    "description": "Brand briefs, visual systems, image-model routing, production prompt packs, and consistency verification.",
    "version": "0.1.0+codex.20260714121935",
    "category": "Design",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Turn this approved positioning into a production-ready brand brief.",
      "Choose the right image model and prompt workflow for this visual job.",
      "Check this image series against the approved brand system."
    ],
    "skills": [
      {
        "name": "brand-brief-builder",
        "description": "Turns approved business context, positioning, audience, references, and deliverables into a production-ready visual brand brief. Use when generating a logo system, identity board, campaign series, or image prompt pack from settled strategy. Validates audience, positioning, visual principles, forbidden drift, and required deliverables without inventing strategy."
      },
      {
        "name": "brand-consistency-verifier",
        "description": "Checks a logo system, identity board, campaign series, or image set against an approved brand brief and reference assets. Use when a visual series needs a release or expansion decision. Records artifact-level findings for composition, color, typography, logo treatment, imagery, and forbidden drift, then validates a pass, fail, or blocked result."
      },
      {
        "name": "brand-model-router",
        "description": "Selects the image model, mode, source requirements, and prompt format for a brand visual job. Use when choosing between GPT Image 2, Nano Banana, Canva, Creative Production, or a no-generation route for identity boards, edits, series, logos, and campaign assets. Validates one model route and records alternatives and missing companions."
      },
      {
        "name": "brand-world-router",
        "description": "Routes brand visual work across decision brief, identity system, image-model selection, production prompt pack, and consistency verification. Use when a brand, campaign, logo system, visual world, or image series needs one coherent production path. Keeps positioning upstream, selects only the skills needed, and validates a primary route before generation."
      },
      {
        "name": "brandkit",
        "description": "Premium brand-kit image generation skill for creating high-end brand-guidelines boards, logo systems, identity decks, and visual-world presentations. Trained for minimalist, cinematic, editorial, dark-tech, luxury, cultural, security, gaming, developer-tool, and consumer-app brand systems. Optimized for intentional logo concepting, refined composition, sparse typography, strong symbolic meaning, premium mockups, art-directed imagery, and flexible grid layouts."
      },
      {
        "name": "gpt-image-2-unified",
        "description": "Prompt architect for GPT Image 2. Generates exactly 7 production-ready Thinking-mode prompts across 11 modes: CREATE (text-to-image), EDIT, SHOW-ME (angle variations), COMPOSE (multi-reference), SEARCH, SERIES (consistent multi-output), TYPOGRAPHY (multilingual/non-Latin), INFOGRAPHIC, EDITORIAL, NARRATIVE (manga, comics, storyboards), MULTI-OUTPUT (multi-page systems sharing one visual DNA). Three formats with auto-detection: natural-language brief (default), JSON envelope with forbidden array (anti-drift, surgical edits, photoreal preservation), system prompt operating contract (single-submission batch generation, up to 8 coordinated outputs sharing one visual DNA). Every format encodes PSGV: Plan, Search or SKIP, Generate, Verify. Variation-axis detection freezes style when angle is requested. Triggers: gpt image 2, openai image prompt, 7 prompts gpt image, brand kit, design bible, json prompt, forbidden array, system prompt for image gen, batch image generation, or any GPT Image 2 prompting request."
      },
      {
        "name": "nano-banana-unified",
        "description": "Unified prompt architect for Gemini 3 Pro Image (Nano Banana). Generates 10 production-ready prompts per query across four modes. CREATE: text-to-image, comics, stickers, icons, infographics, data viz. EDIT: image editing, style transfer, inpainting, show-me angles, multi-reference composition, character transformation. BRAND: brand design, identity systems, logo treatments, mockups, apparel, typography, capsule collections, 35+ brand use cases with DNA extraction. GRID: 6-9 image campaign grids, moodboards, visual systems using Gizem methodology. Backed by 43+ use case patterns, 127 creative directions, texture library, and official Google templates. Triggers: nano banana, gemini image, generate image, create image, image prompt, edit this image, show me angles, brand design, brand identity, brand mockup, logo treatment, brand visualization, capsule collection, grid, campaign grid, moodboard, comic, sticker, infographic, diagram, product concept, or any Gemini image generation request."
      }
    ],
    "counts": {
      "skills": 7,
      "assets": 9,
      "references": 23,
      "scripts": 7,
      "files": 65
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "founder-revenue-engine",
    "name": "Founder Revenue Engine",
    "shortDescription": "Turn market signals into evidence-backed early revenue work.",
    "longDescription": "Founder Revenue Engine converts recent market signals into a bounded ICP, commercial narrative, outreach drafts, and founder-led content while keeping sends and account changes unauthorized by default.",
    "description": "Signal research, ICP definition, commercial narrative, bounded outreach drafts, and founder-led content.",
    "version": "0.1.0+codex.20260714121935",
    "category": "Sales",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Research recent signals and build an evidence-backed early-customer hypothesis.",
      "Turn this validated ICP into a commercial narrative.",
      "Draft a bounded outreach sequence without sending anything."
    ],
    "skills": [
      {
        "name": "first-customer-finder",
        "description": "Find and qualify evidence-backed potential first customers, early adopters, design partners, or beta users for a startup using recent public pain and buying signals. Use when Codex needs to analyze a product URL or idea, define an ideal customer profile, research public discussions and business pages, identify first-user prospects, rank lead fit and timing, prepare source-based outreach drafts, or create a shareable early-customer prospecting report without sending messages automatically."
      },
      {
        "name": "founder-revenue-router",
        "description": "Routes founder-led revenue work across recent signal research, ideal-customer profiling, market narrative, outreach sequence, and LinkedIn content. Use when a founder needs evidence-backed early customers, design partners, a commercial message, or bounded outreach drafts. Enforces source traceability and never sends, writes CRM data, or changes accounts without separate action-time authorization."
      },
      {
        "name": "last30days",
        "description": "Research what people actually say about any topic in the last 30 days. Use when recent public conversations, engagement, market language, or source-backed trends are needed from Reddit, X, YouTube, TikTok, Hacker News, Polymarket, GitHub, and the web. Includes a doctor health check to diagnose broken or missing sources."
      },
      {
        "name": "linkedin-viral-content-creator",
        "description": "Create viral LinkedIn posts combining probability-driven consensus-breaking with 69 proven templates and complete post workflow. Use when writing LinkedIn posts, creating hooks, improving drafts, or generating contrarian content. Enforces no-fabrication rule and a configurable voice profile. Six-phase workflow maps consensus, generates hooks via dual method (tail sampling plus templates), applies PRISM humanization, writes body, enforces quality, and delivers multiple options with rationale."
      },
      {
        "name": "market-narrative-builder",
        "description": "Builds a source-traceable commercial narrative that connects a specific audience problem, market language, offer, proof, objections, and call to action. Use when a defined ICP must become outreach, sales copy, founder content, or campaign assets. Validates that claims come from the allowed evidence set and keeps unsupported proof out of the message."
      },
      {
        "name": "outreach-sequence-builder",
        "description": "Drafts a bounded, evidence-linked outreach sequence for early customers, design partners, beta users, or founder-led conversations. Use when the ICP and market narrative are approved and channel-specific messages are needed. Produces messages with objectives, source references, stop rules, and no-send enforcement. It never sends email, updates CRM records, or changes accounts."
      },
      {
        "name": "signal-to-icp",
        "description": "Converts recent public pain, buying, engagement, and language signals into an evidence-backed ideal-customer profile with disqualifiers, confidence, and verification gaps. Use when market research or first-customer discovery must become a bounded ICP hypothesis instead of a generic persona. Validates source-linked signals and unique evidence records."
      }
    ],
    "counts": {
      "skills": 7,
      "assets": 8,
      "references": 16,
      "scripts": 115,
      "files": 153
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "continuity-vault",
    "name": "Continuity Vault",
    "shortDescription": "Keep reusable knowledge findable and trustworthy.",
    "longDescription": "Continuity Vault routes work through source-preserving extraction, governed promotion, relationship mapping, recall, and staleness audits while keeping workspace files authoritative.",
    "description": "Source-preserving extraction, knowledge promotion, graph routing, recall, and staleness auditing.",
    "version": "0.1.0+codex.20260714121935",
    "category": "Productivity",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Extract reusable knowledge from this source without replacing it.",
      "Decide where this knowledge belongs and preserve its authority.",
      "Audit these sources for staleness and instruction conflicts."
    ],
    "skills": [
      {
        "name": "continuity-router",
        "description": "Routes continuity work across extraction, durable-file promotion, knowledge graphs, memory search, staleness audits, and digests. Use when work from tasks, projects, or research must remain findable and trustworthy across future Codex sessions. Keeps workspace files as authority, treats memory and Chronicle as recall only, and does not overwrite or delete source material."
      },
      {
        "name": "frontier-extraction",
        "description": "Extract a frontier model's judgment into durable artifacts before access ends, pricing changes, or a model window closes. Applies the irreversibility test (can a cheaper model redo this tomorrow, if yes skip it) then routes across five moves. WORKSPACE rewrites CLAUDE.md and skills as an operating manual a weaker model can execute. AUDIT runs a consultant-grade business audit into an executable roadmap. VAULT atomizes deep research into one-insight linked notes. GOALS fires capped, evidence-gated goal runs on the highest-value backlog. RECORDER installs an extract-approach habit that writes a learnings note per solved problem. Use when the user says extract before it is gone, last day with this model, bank this model's judgment, distill the model, write the standard down, make this survive the model change, or wants session learnings captured automatically."
      },
      {
        "name": "graphify",
        "description": "Use for any question about a codebase, its architecture, file relationships, or project content - especially when graphify-out/ exists, where the question should be treated as a graphify query first. Turns any input (code, docs, papers, images, videos) into a persistent knowledge graph with god nodes, community detection, and query/path/explain tools."
      },
      {
        "name": "knowledge-promotion-policy",
        "description": "Decides whether extracted knowledge belongs in a durable file, project reference, graph, memory candidate, or nowhere. Use when reusable context needs a governed destination with provenance, ownership, staleness review, and authority preserved. It recommends or records a promotion decision but does not rewrite authoritative sources without explicit scope."
      },
      {
        "name": "staleness-and-conflict-audit",
        "description": "Audits a bounded source set for stale claims, conflicting instructions, broken authority assumptions, and unresolved ownership. Use when prior plans, memories, prompt guidance, plugin records, or operating rules may be reused. Produces read-only findings with evidence and recommended review actions. It never resolves a conflict by silently editing or deleting a source."
      }
    ],
    "counts": {
      "skills": 5,
      "assets": 7,
      "references": 12,
      "scripts": 5,
      "files": 39
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "data-storytelling-studio",
    "name": "Data Storytelling Studio",
    "shortDescription": "Turn checked analysis into decision-facing stories.",
    "longDescription": "Data Storytelling Studio preserves the analytical source of truth while routing it to the right delivery format, auditing visual claims, and producing an answer-first executive readout with explicit evidence and caveats.",
    "description": "Routes checked analysis into decision-facing visual stories, executive readouts, reports, decks, dashboards, and publishable sites.",
    "version": "0.1.0+codex.20260714130032",
    "category": "Productivity",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Choose the right output format for this checked analysis.",
      "Audit whether each chart supports the claim beside it.",
      "Turn this evidence into an executive readout with decisions and caveats."
    ],
    "skills": [
      {
        "name": "analysis-to-story-router",
        "description": "Routes checked analysis to the right notebook, chart, dashboard, report, deck, executive readout, or publishable site. Use when the user has data findings or an analysis artifact and needs to choose a decision-facing format, audience, companion tools, evidence limits, and handoff path before production."
      },
      {
        "name": "chart-message-audit",
        "description": "Audits whether each chart, dashboard panel, diagram, or visual caption supports its stated conclusion. Use when reviewing analytical visuals for evidence alignment, scale and denominator problems, misleading encodings, missing uncertainty, accessibility, or a publish, revise, or block decision."
      },
      {
        "name": "executive-readout-builder",
        "description": "Builds an answer-first executive readout from checked evidence, with decisions, risks, caveats, and next actions. Use when analysis must become a concise leadership memo, meeting readout, decision brief, report summary, or deck narrative without introducing unsupported claims."
      }
    ],
    "counts": {
      "skills": 3,
      "assets": 6,
      "references": 3,
      "scripts": 6,
      "files": 24
    },
    "bundlesMcp": false,
    "bundlesApp": false
  },
  {
    "slug": "model-evaluation-lab",
    "name": "Model Evaluation Lab",
    "shortDescription": "Plan, run, normalize, and decide model evaluations.",
    "longDescription": "Model Evaluation Lab turns a model choice into a fixed evaluation plan, a reproducible run contract, normalized results, and a decision memo that separates measurement from judgment and deployment conditions.",
    "description": "Plans reproducible model evaluations, normalizes benchmark runs, and produces measured model-selection decisions.",
    "version": "0.1.0+codex.20260714130940",
    "category": "Developer Tools",
    "license": null,
    "capabilities": [],
    "defaultPrompts": [
      "Design a reproducible evaluation for this model decision.",
      "Normalize these raw benchmark results into a stable comparison.",
      "Write a model-selection memo that separates results from judgment."
    ],
    "skills": [
      {
        "name": "benchmark-runner",
        "description": "Executes or delegates a frozen model evaluation plan, records reproducible run conditions, and normalizes raw case results into a stable comparison schema. Use when running model, prompt, agent, or tool benchmarks locally or through Hugging Face jobs, or when completed raw runs need validation and aggregation."
      },
      {
        "name": "model-evaluation-plan",
        "description": "Creates a reproducible model evaluation plan with a fixed decision, baselines, candidates, representative cases, metrics, budget, environment, execution backend, and stopping rules. Use when preparing to compare models, prompts, agents, tool behavior, migrations, or deployment configurations."
      },
      {
        "name": "model-evaluation-router",
        "description": "Routes model evaluation work across planning, benchmark execution or result normalization, and model-selection decisions. Use when a model, prompt, agent, tool, or deployment comparison is new, spans several stages, has unclear prerequisites, or needs the next safe evaluation step."
      },
      {
        "name": "model-selection-memo",
        "description": "Produces a model-selection memo that separates measured benchmark results from judgment, tradeoffs, limitations, cost interpretation, and deployment conditions. Use when comparable evaluation runs are complete and a deployment, migration, rollback, or no-decision recommendation is needed."
      }
    ],
    "counts": {
      "skills": 4,
      "assets": 8,
      "references": 4,
      "scripts": 8,
      "files": 31
    },
    "bundlesMcp": false,
    "bundlesApp": false
  }
] as const;
export const totals = {
  "plugins": 15,
  "skills": 102,
  "assets": 251,
  "references": 372,
  "scripts": 307,
  "files": 1237
} as const;
export type Plugin = (typeof plugins)[number];
